ConfigurableTricks = [
  Trick_1234
  Trick_180Varial
  Trick_2KickMadonnaFlip
  Trick_360FlipNoseManual
  Trick_360Varial
  Trick_360VarialMcTwist
  Trick_4thofJuly
  Trick_50FingerFlip
  Trick_540Flip
  Trick_540TailWhip
  Trick_AirCasperFlip
  Trick_Airwalk
  Trick_AmericanHeroGrind
  Trick_AndrectInvert
  Trick_AntiCasper
  Trick_AssumePosition
  Trick_AxleStall
  Trick_BackfootHeelflip
  Trick_BackfootKickflip
  Trick_BackFootNosegrab
  Trick_BarrelRoll
  Trick_BballSlide
  Trick_Beanplant
  Trick_Benihana
  Trick_BetweenLegsSlam
  Trick_BetweenTheLegs
  Trick_BigHitter
  Trick_BigSpinFliptoTail
  Trick_BigSpinShifty
  Trick_BloodyEddie
  Trick_Blunt
  Trick_Bodywrap540
  Trick_Boneless
  Trick_BoomBox
  Trick_BSFootplant
  Trick_BSNoseComply
  Trick_Burntwist
  Trick_Cannonball
  Trick_CartwheelTo5050
  Trick_Casper
  Trick_ChompOnThis
  Trick_ChristAir
  Trick_Coffin
  Trick_Crail
  Trick_CrailSlide
  Trick_CrookedBigSpin
  Trick_CrookedBigSpinFlip
  Trick_CrookedCop
  Trick_Crossbone
  Trick_DaffyBrokenGrind
  Trick_DanceParty
  Trick_DarkDisaster
  Trick_DarkSlide
  Trick_DelMarIndy
  Trick_Disaster
  Trick_DoubleBluntSlide
  Trick_DoubleKFindy
  Trick_Eggplant
  Trick_ElbowSmash
  Trick_FalconSlide
  Trick_Fandangle
  Trick_Fastplant
  Trick_FeebleLayback
  Trick_FerretGrind
  Trick_FFImpossible
  Trick_Fingerflip
  Trick_FingerFlipAirWalk
  Trick_Flamingo
  Trick_FlipKickDad
  Trick_FroggyGrind
  Trick_FS540
  Trick_FS540HeelFlip
  Trick_FSShifty
  Trick_FSShoveIt
  Trick_Gazelle
  Trick_GhettoBird
  Trick_GrappleGrab
  Trick_GrindOverturn
  Trick_Gturn
  Trick_Gturn2
  Trick_GuitarSlide
  Trick_GymnastPlant
  Trick_HalfCabImpossible
  Trick_Handstand
  Trick_Handstand5050
  Trick_HandStand50Flip
  Trick_HandstandDoubleFlip
  Trick_HangTenNoseGrind
  Trick_Hardflip
  Trick_HardFlipBackFootFlip
  Trick_Heelflip
  Trick_HeelflipFSInvert
  Trick_HeelFlipHandflip
  Trick_HFVarialLien
  Trick_HoHoSadplant
  Trick_HoHoStreetPlant
  Trick_HulaHoop
  Trick_HumanDart
  Trick_Hurricane
  Trick_Impossible
  Trick_Indy
  Trick_Indy900
  Trick_IndyNosebone
  Trick_Invert
  Trick_InwardHeelflip
  Trick_Jackass
  Trick_Japan
  Trick_Judo
  Trick_JudoMadonna
  Trick_JumpJets
  Trick_KFBackflip
  Trick_KFIndy
  Trick_KFMelon
  Trick_KFSuperman
  Trick_Kickflip
  Trick_KickFlipOneFootTail
  Trick_KickFlipUnderFlip
  Trick_LazyAss
  Trick_Madonna
  Trick_Manual
  Trick_McTwist
  Trick_Melon
  Trick_Method
  Trick_MightAsWellJump
  Trick_MistyFlip
  Trick_MPCGrind
  Trick_Mute
  Trick_MuteInvert
  Trick_NoComplyLate360
  Trick_NollieFlipUnderflip
  Trick_Noseblunt
  Trick_NosebonePoker
  Trick_Nosegrab
  Trick_NosegrindPivot
  Trick_NoseManual
  Trick_Nosepick
  Trick_NoseSlideLipSlide
  Trick_OllieAirwalk
  Trick_OllieNorth
  Trick_OneFootBlunt
  Trick_OneFootInvert
  Trick_OneFootJapan
  Trick_OneFootManual
  Trick_OneFootNosemanual
  Trick_OneFootOneWheel
  Trick_OneFootSmith
  Trick_OneFootTailgrab
  Trick_Pogo
  Trick_PogoFlip
  Trick_PopShoveIt
  Trick_PrimoSlide
  Trick_QuadrupleHeelFlip
  Trick_QuickDraw
  Trick_ReemoSlide
  Trick_Rocket
  Trick_RocketTailslide
  Trick_RockOutGrind
  Trick_RockToFakie
  Trick_RowleyDarkSlide
  Trick_Russian
  Trick_RustySlide
  Trick_SackTap
  Trick_Salad
  Trick_SalFlip
  Trick_SambaFlip
  Trick_SaranWrap
  Trick_Seatbelt
  Trick_SemiFlip
  Trick_SitDownAir
  Trick_SplitsManual
  Trick_SprayPaintGrind
  Trick_Sproing
  Trick_StageDive
  Trick_StaleBackFlip
  Trick_Stalefish
  Trick_Stalefish_Layback
  Trick_StaleFrontFlip
  Trick_Stiffy
  Trick_Sunbathin
  Trick_Switcheroo
  Trick_SwitchFootPogo
  Trick_TailblockSlide
  Trick_Tailgrab
  Trick_The900
  Trick_ToRail
  Trick_Truckstand
  Trick_VarialHeelflip
  Trick_VarialKickflip
  Trick_Layout
  Trick_MaulForceGrab
  Trick_RodeoClown
  Trick_SuperHandClap
  Trick_WorkForFood
  Trick_ACAir
  Trick_PizzaGuy
  Trick_Berzerker
  Trick_ClawPunch
  Trick_Roastbeef
  Trick_ZZZZManual
  Trick_DuckDive
  Trick_VisitingHome
  Trick_WorkForFoodManual
  Trick_Drunkgrind
  Trick_MaulRollGrind
  Trick_PaddleGrind
  Trick_Sobriety
  Trick_Varial
  Trick_HTeethSweeper
  Trick_Summoner
  Trick_VarialKickflip2
]
